### ISSUE TITLE
Add option to remove I-frame

### ISSUE THREAD

**Issue by Jawaji** [delthas/vegas-datamosh#1]

**Comment by delthas** [comment]
details please

**Comment by Jawaji** [comment]
make a script that can remove all or most I-frame from selected region

**Comment by Jawaji** [comment]
;(

**Comment by delthas** [comment]
so, i can essentially choose which frames should be I frames and which ones should be P, when rendering. (or rather, the first rendered frame is an I frame so you could choose when the first I frame is, and afterwards you get a fixed interval between all subsequent I frames, which is called GOP length and you can choose it when rendering.)


given that, which interval do you think i should choose to render I frames (to delete them afterwards)? and what would the parameters be?

**Comment by delthas** [comment]
added in #fbaa37f (datamix script)
