### ISSUE TITLE
Access to the path: "[folderpath]\config_datamosh.js" is denied.

### ISSUE THREAD

**Issue by QuilloManar** [delthas/vegas-datamosh#6]
![image](https://user-images.githubusercontent.com/30070287/93336980-d790c680-f86b-11ea-8958-1c18bc3069b2.png)
Did I do something wrong? This is what happens when I try to use both Datamoshing and Datamixing. Also, there is no folder 'Vegas Scripts' in my documents folder, it's just on my C drive in the Vegas folder, as shown in the dialogue box.

**Comment by eskolzz** [comment]
run as admin

**Comment by delthas** [comment]
The README says to unpack the files into your C:\Users\<user>\Documents\Vegas Script Menu folder, not Program Files.
